# Settings for the [build] key are global and are applied to
# all deploy contexts unless overridden by a context-specific setting.
[build]
  base = "project/"
  publish = "build-output/"
  command = "echo 'default context'"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[context.production]
  publish = "output/"
  command = "make publish"
  environment = { NODE_VERSION = "14.15.3" }

[context.deploy-preview]
  publish = "dist/"

[context.deploy-preview.environment]
  NOT_PRIVATE_ITEM = "not so secret"

[context.branch-deploy]
  command = "echo branch"
[context.branch-deploy.environment]
  NODE_ENV = "development"

[context.dev.environment]
  NODE_ENV = "development"

[context.staging]
  command = "echo 'staging'"
  base = "staging"

[context."feat/branch"]
  command = "echo 'special branch'"
  base = "branch"

[[redirects]]
  from = "/*"
  to = "/blog/:splat"

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 302
  force = true
  query = { id = ":id" }
  conditions = { Language = ["en"], Country = ["US"] }
  signed = "API_SIGNATURE_TOKEN"
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"

[[redirects]]
  from = "/gated-path"
  status = 200
  conditions = { Role = ["admin"] }
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
    Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"

[functions]
  directory = "functions/"

[dev]
  command = "yarn start"
  port = 8888
  targetPort = 3000
  publish = "dist"
  jwtRolePath = "app_metadata.authorization.roles"
  jwtSecret = "MY_JWT_SECRET_VALUE"
  autoLaunch = true
  framework = "#custom"
  [dev.https]
    certFile = "cert.pem"
    keyFile = "key.pem"
